In [218]:
from PIL import Image
import numpy as np


In [219]:

height = 20
weight = 1000
channel = 3
img_numpy = np.random.randint(0, 256, (height, weight, channel)).astype(np.uint8)
img = Image.fromarray(img_numpy, "RGB")
# make a numpy array of random numbers of shape (20,100,3) and type uint8
img_numpy.shape
img_numpy


array([[[ 99, 139, 208],
        [124, 156, 169],
        [  9, 104,  50],
        ...,
        [227, 158,  38],
        [126, 150, 241],
        [226,  64,  20]],

       [[251, 183, 100],
        [ 60, 215, 204],
        [225,   3, 128],
        ...,
        [124,  63, 185],
        [168, 123, 155],
        [ 77,  39, 136]],

       [[207, 194,  51],
        [174,   2, 230],
        [ 16, 213, 176],
        ...,
        [ 81, 168, 207],
        [ 75, 104, 120],
        [  3, 241, 124]],

       ...,

       [[ 60, 253,  91],
        [193, 162, 195],
        [ 66, 173, 219],
        ...,
        [127, 180,   4],
        [101,  24, 233],
        [131, 106,  35]],

       [[246, 127, 114],
        [156,  83, 147],
        [ 11, 138, 125],
        ...,
        [155, 132, 138],
        [224, 190, 227],
        [  6, 102, 159]],

       [[234,  94, 145],
        [241,  35, 145],
        [ 38, 254,  82],
        ...,
        [173,   0, 213],
        [212,  68, 165],
        [214, 211, 240]]

In [220]:


# Save the Numpy array as Image
image_filename = "opengenus_image.jpeg"
img.save(image_filename)


In [221]:
#import csv and save contents to dataframe
import pandas as pd
df = pd.read_csv('example_data_top4.csv')

#removing column 2
df = df.drop(df.columns[1], axis=1)


In [222]:
def convert_value_to_rgb(value,m,n):
    min_value = n
    max_value = m

    normalized_value = (value - min_value) / (max_value - min_value)
    rgb_value = int(normalized_value * 255)

    rgb = (rgb_value, rgb_value, rgb_value)

    return rgb

#convert a 1d dataframe to a array of int
df = np.random.exponential(3.45, 10000)
n = min(df)
m = max(df)
# Convert each value to RGB
rgb_array = np.array([convert_value_to_rgb(value,m,n) for value in df])

#sort this np array in ascending order basing on first value
rgb_array = rgb_array[rgb_array[:,0].argsort()]

#drop the last 6 values
rgb_array=rgb_array.reshape(40,250,3)
print(rgb_array)

img = Image.fromarray(rgb_array, "RGB")
image_filename = "new.jpeg"
img.save(image_filename)


[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 ...

 [[ 61  61  61]
  [ 61  61  61]
  [ 61  61  61]
  ...
  [ 72  72  72]
  [ 72  72  72]
  [ 72  72  72]]

 [[ 72  72  72]
  [ 72  72  72]
  [ 72  72  72]
  ...
  [ 89  89  89]
  [ 89  89  89]
  [ 89  89  89]]

 [[ 89  89  89]
  [ 89  89  89]
  [ 89  89  89]
  ...
  [194 194 194]
  [214 214 214]
  [255 255 255]]]
